version: "3"

services:

  app:
    container_name: extractor
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    networks:
      - default
    ports:
      - ${GRADIO_SERVER_PORT}:${GRADIO_SERVER_PORT}

    env_file: .env

networks:
  default:
      driver: bridge
      name: streaming-transcription

